/* eslint-disable no-unused-vars */
import Head from 'next/head'
import { useSession } from 'next-auth/client'
import SignInForm from '../components/signinForm'

export default function Home () {
  const [session, loading] = useSession()

  return (
    <div>
      <Head>
        <title>Next App Template</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {loading &&
        <h1>Loading...</h1>
      }

      {!loading && session &&
        <h1>Welcome!</h1>
      }

      {!loading &&
        <SignInForm session={session}></SignInForm>
      }
    </div>
  )
}
